on:
  - pull_request_target

name: Pull Request Target (All types)

env:
  IN_MAINTAINER_LIST: ${{ contains(secrets.MAINTAINER_LIST, github.actor) }}

jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply Labels
        uses: actions/labeler@v4.2.0
        with:
          configuration-path: .github/labeler-pr-triage.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  NeedsTriageLabeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Apply needs-triage Label
        uses: actions/labeler@v4.2.0
        if: github.event.action == 'opened' && env.IN_MAINTAINER_LIST == 'false' && github.actor != 'dependabot[bot]'
        with:
          configuration-path: .github/labeler-pr-needs-triage.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  SizeLabeler:
    runs-on: ubuntu-latest
    steps:
      # See also: https://github.com/CodelyTV/pr-size-labeler/pull/26
      - name: Apply Size Label
        uses: codelytv/pr-size-labeler@v1.8.1
        # uses: bflad/pr-size-labeler@d56e9ca5fe93539a256a7e7b4efd971f4f19fe00
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: '30'
          s_label: 'size/S'
          s_max_size: '60'
          m_label: 'size/M'
          m_max_size: '150'
          l_label: 'size/L'
          l_max_size: '300'
          xl_label: 'size/XL'
          message_if_xl: ''
