name: review
on: [pull_request, issues]


jobs:
  first-interaction:
    permissions:
      pull-requests: write
      issues: write
    name: runner / first-interaction
    runs-on: ubuntu-latest
    steps:
      - name: first-interaction
        uses: actions/first-interaction@v1.1.1
        if: github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Welcome @${{github.actor}} :wave: Thanks for opening your first issue!
          pr-message: |
            # Welcome @${{github.actor}} :wave: !

            Thank you for opening your first pull request! :tada Please ensure you have read the full `CONTRIBUTING.md` guide before continuing.

            ## What's next?

            The next steps to getting this pull request deployed are as follows:

            1. Ensure that all CI checks are successful
            2. Request review on your pull request and obtain an approval
            3. Merge your pull request! ✨

            ## Deployment

            Once you merge your pull request to the `main` branch a deployment will be automatically triggered for you.

            In roughly ~5 minutes your changes will deployed to production

            That's all! Thanks for contributing! :smiley:
