name: Workflow Linting
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/*
jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run actionlint on workflow files
        run: docker run --rm -v "$PWD:/repo" --workdir /repo rhysd/actionlint:latest -color
